### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by jdolan** [alexjball/json-dom#1]
Hey Alex,

Love the thought and effort you've put into this exercise so far. Unit tests and CI -- that's just great. It also looks to be well organized, and I love that you went for the extra credit.

I tried to run the exercise this morning and ran into a snag:
```
(base) The-Dark-Zone:json-dom jdolan$ ./cli.js --file SystemViewController.json 
Selector to query: #videoMode
Couldn't match selector SyntaxError: Invalid regular expression: /(?<viewClass>[\w]+)?(?<classNames>(?:\.[\w\-]*)*)(?:#(?<identifier>[\w\-]+))?/: Invalid group
    at Function._parseRule (/private/tmp/json-dom/JsonDom.js:73:32)
    at JsonDom.matchSelector (/private/tmp/json-dom/JsonDom.js:110:26)
    at terminal.question.rule (/private/tmp/json-dom/cli.js:23:32)
    at Interface._onLine (readline.js:278:5)
    at Interface._line (readline.js:629:8)
    at Interface._ttyWrite (readline.js:910:14)
    at ReadStream.onkeypress (readline.js:158:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
```

That should be a valid selector, so I was wondering if you wanted to take a quick stab at fixing that regex issue before we speak on the phone. Looking forward to next steps.

**Comment by alexjball** [comment]
Hey Jay,

Thanks bringing this up! It looks like that error is because your version of Node (below v10) doesn't support [named capture groups](https://node.green/#ES2018-features--RegExp-named-capture-groups).

- [update the matching logic](https://github.com/alexjball/json-dom/commit/6cf3951841064c1c9e6a058a96dcda5c78722162) not to use named capture groups
- update Travis to run tests against Node 6-13. 
- add error text for invalid rules.

Node v6 is the lowest version that works--v4 doesn't support optional function args. Let me know if you continue to see issues using the script.

**Comment by jdolan** [comment]
Yup, I'm running Node 8.16.2. Works now. Nicely done!
